services:

    db:
      image: mysql:latest
      ports:
        - "3306:3306"
      volumes:
        - db_data:/var/lib/mysql
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: pass
        MYSQL_DATABASE: test_database
        MYSQL_USER: user
        MYSQL_PASSWORD: pass
      healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$MYSQL_ROOT_PASSWORD"]
        interval: 30s
        timeout: 5s
        retries: 6
        start_period: 30s



    app:
      image: sb-app  # 使用するDockerイメージの名前
      depends_on:
        db:
          condition: service_healthy
      build:
        context: spring-boot-docker/  # Dockerfile のあるディレクトリを指定
        dockerfile: Dockerfile  # ビルドに使うDockerfileのパス
      ports:
        - "8081:8080"  # ホストの8081ポートをコンテナの8080ポートにマッピング

volumes:
  db_data: